# Generated by Django 4.0.3 on 2022-03-22 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCategories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('qualifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_api.qualifications')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.IntegerField(choices=[(0, 'Admin'), (1, 'Device Manager'), (2, 'Operator'), (3, 'Repairman')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('severity', models.IntegerField(choices=[(0, 'Not Urgent'), (1, 'Slightly Severe'), (2, 'Moderately Severe'), (3, 'Severe'), (4, 'Urgent')], default=0)),
                ('scheduled_maintenance', models.DateTimeField()),
                ('current_state', models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Declined'), (2, 'Accepted'), (3, 'Started'), (4, 'Finished')], default=0)),
                ('task_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_api.taskcategories')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_api.users')),
            ],
        ),
        migrations.CreateModel(
            name='RepairmanQualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_api.qualifications')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('task_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_api.taskcategories')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='db_api.taskcategories')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='db_api.taskcategories')),
            ],
        ),
    ]
