# Generated by Django 4.0.3 on 2022-03-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryConnections',
            new_name='CategoryConnection',
        ),
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
        migrations.RenameModel(
            old_name='Qualifications',
            new_name='Qualification',
        ),
        migrations.RenameModel(
            old_name='RepairmanQualifications',
            new_name='RepairmanQualification',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='TaskCategories',
            new_name='TaskCategory',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
