# Generated by Django 4.0.3 on 2022-03-22 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0002_rename_categoryconnections_categoryconnection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.TextField(default='location'),
        ),
        migrations.AddField(
            model_name='task',
            name='periodic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='instructions',
            field=models.TextField(default='instruction'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='maintenance_period_in_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='time_in_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_maintenance',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
