# Generated by Django 4.0.3 on 2022-03-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0004_alter_device_id_alter_qualification_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryconnection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
