# Generated by Django 4.0.3 on 2022-03-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0006_task_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_category_id',
            new_name='task_category',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
